version: "3"

services:
  ftp-server:
    image: stilliard/pure-ftpd:latest
    
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: 192.168.1.31
      FTP_USER_NAME: "ftp-user"
      FTP_USER_PASS: "ftpuser"
      FTP_USER_HOME: "/home/ftpuser"
      MIN_PASSIVE_PORT: 30000
      MAX_PASSIVE_PORT: 30009
      
 

    restart: always
    
    
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3306:3306
    
    environment:
     - MYSQL_ROOT_PASSWORD=guessitplease
     - MYSQL_DATABASE=erppro
     - MYSQL_USER=root
     - MYSQL_PASSWORD=guessitplease
    command: --bind-address=0.0.0.0
    volumes:
      - db_data:/var/lib/mysql
     
    
     
  python_app:
    image: naderbessioud/nadfactds:latest
    restart: on-failure
    container_name: nadfactds
    ports:
     - 5000:5000
    
    depends_on:
     - mysqldb
    
  spring_app:
    image: naderbessioud/nadfactspring:latest
    network_mode: host
    container_name: nadfactspring
    restart: on-failure
    
    environment:
     
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://192.168.1.17:3306/erppro?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "guessitplease",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "create"
      }'
      
      
      
    ports:
     - 8082:8082
    depends_on:
     - mysqldb
     - ftp-server
     - python_app
     
     
volumes:
 db_data:
